new Vue({
	el: '#llama',
	data: {
		header: 'Fun facts about llamas',
		items:[
	     'LLAMAS ARE MAMMALS',
		 'LLAMAS ARE HERBIVORES MEANING THEY ONLY EAT PLANTS',
		 'LLAMAS ONLY NEED TO DRINK A SMALL AMOUNT OF WATER',
		 'LLAMAS LIVE IN THE ANDES MOUNTAIN REGION ALONG THE WEST COAST OF SOUTH AMERICA',
		 'LLAMAS ARE RELATED TO CAMELS',
		 'LLAMAS CAN LIVE BETWEEN 15-30 YEARS',
		 'A FULL GROWN LLAMA CAN WEIGH BETWEEN 280-500 POUNDS',
		 'MOTHER LLAMAS ARE PREGNANT FOR 11 1/2 MONTHS',
		 'THEY GIVE BIRTH STANDING UP TO USUALLY ONE BABY CALLED A CRIA',
		 'LLAMAS ARE KNOWN TO SPIT WHEN THEY FEEL THREATENED'
		]
	}
});